### ISSUE TITLE
Last Step: Deploy!

### ISSUE THREAD

**Issue by gschorkopf** [frolfr/frolfr-client#12]
http://blog.firstiwaslike.com/deploying-ember-cli-apps/
https://github.com/ember-cli/ember-deploy
https://github.com/achambers/ember-cli-deploy

**Comment by gschorkopf** [comment]
https://github.com/ember-cli/ember-cli-deploy seems to be the way of the future.

**Comment by gschorkopf** [comment]
ZOMG so close

**Comment by killpack** [comment]
Do you have an S3 bucket already?

**Comment by killpack** [comment]
Also, if you don't want to pay for Redis, here's a possibility (maybe): http://kerrygallagher.co.uk/deploying-an-ember-cli-application-to-amazon-s3/

**Comment by killpack** [comment]
In that case, you'd change your DNS such that frolfr.com would point to your S3 bucket, rather than your Heroku app.

**Comment by gschorkopf** [comment]
Word. Well I do have an S3 bucket for all 7 of our course photos.

**Comment by killpack** [comment]
Cool. I'm assuming you don't want to shell out for Redis? Let's give the pure-S3 approach a try!
