### ISSUE TITLE
Font awesome icons not showing

### ISSUE THREAD

**Issue by gschorkopf** [frolfr/frolfr-client#14]
Error message: "Font from origin 'http://s3.amazonaws.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://frolfr.com' is therefore not allowed access."

**Comment by killpack** [comment]
Resolution: change CORS configuration in s3 asset bucket.
